apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: default
spec:
  containers:
    - image:  kodekloud/simple-webapp-mysql
      imagePullPolicy: Always
      name:  webapp-mysql
      envfrom:
      - secretRef:
          name: db-secret
