apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-replicaset
  labels:
    app: guestbook
    tier: jhyoon-test-replicaset
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: jhyoon-test-replicaset
  template:
    metadata:
      labels:
        tier: jhyoon-test-replicaset
    spec:
      containers:
      - name: test-web
        image: nginx:latest
        resources:
         ports:
           - containerPort: 80
        command: [ "/bin/bash", "-c", "--", "apt-get update", "apt-get install nginx"]
        args: [ "while true; do sleep 30; done;" ]

      - name : test-app
        image: ubuntu:21.04
        resource:
          ports:
            - containerPort: 80
        command: [ "/bin/bash", "-c", "--", "apt-get update", "apt-get install nginx"]
        args: [ "while true; do sleep 30; done;" ]
