apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
  labels:
    location: local
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /pv/log

