apiVersion: apps/v1
kind: Service
metadata:
  name: messaging-service
spec:
  type: ClusterIP
  selector:
    tier: msg
  ports:
    port:  6379
    protocol: TCP

#Command
#kubectl expose pod messaging --type=ClusterIP --port=6379 --labels="tier=msg"