apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: elastic-stack
spec:
  containers:
    - image:  kodekloud/event-simulator
      name: app 
      volumeMounts:
        - name:  log-volume
        mountPath: /log
    - image: kodekloud/filebeat-configured
      name: sidecar
      volumeMounts:
        - name:  log-volume
        mountPath:  /var/log/event-simulator