kind: Service
apiVersion: v1
metadata:
  name:  back-end
spec:
  selector:
    app:  
  type:  ClusterIP
  ports:
  - name:  ClusterIP-backend
    port:  80
    targetPort:  8080
  selector:
    app: myapp
    type: back-end