kind: Service
apiVersion: v1
metadata:
  name:  back-end
spec:
  selector:
    app:  
  type:  LoadBalancer
  ports:
  - name:  LoadBalancer-backend
    port:  80
    targetPort:  8080
  selector:
    app: myapp
    type: back-end