apiVersion: v1
kind: Service
metadata:
  name:  myapp-service
spec:
  selector:
  type:  NodePort
  ports:
  - targetPort: 80
    port:  80
    targetPort:  30008
  selector:
    app: myapp
    type: front-end

